server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
spring:
  application:
    name: erueka-server